# Generated by Django 4.2.4 on 2023-09-01 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.CharField(max_length=7)),
                ('autor', models.CharField(max_length=100)),
                ('titulo', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.titulo')),
            ],
        ),
    ]
